version: "3.10"

services:

  app:
    container_name: as-app
    image: image-classifaier
    build:
      context: ./
    ports:
      - "5000:5000"
    working_dir: /app
    command: flask run --host=0.0.0.0
#    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - as

networks:
  as:
    driver: bridge